### ISSUE TITLE
Attempting to drag in Safari and IE selects text on page

### ISSUE THREAD

**Issue by mccambridge** [clauderic/react-sortable-hoc#253]
When I drag an item in Safari or IE 11, the text on other areas of the page that my mouse travels by gets selected. It's as if the browser doesn't know I'm dragging but things my mouse went down for the purpose of highlighting text on the page.

Great hoc! I definitely appreciate your work! :D

**Comment by wahabshah** [comment]
Firefox and IE both have the same problem of a drag causing selection.
The solution I found is just two steps:-

1. Define the following css  class :-


 ```css
  .noselect {
  -webkit-touch-callout: none; /* iOS Safari */
    -webkit-user-select: none; /* Safari */
     -khtml-user-select: none; /* Konqueror HTML */
       -moz-user-select: none; /* Firefox */
        -ms-user-select: none; /* Internet Explorer/Edge */
            user-select: none; /* Non-prefixed version, currently
                                  supported by Chrome and Opera */
 }
```
2. Apply the css class on your SortableItem component (div or li which you will drag) like so :-

```javascript
const SortableItem = SortableElement(({value,SortableItemClassName}) =>
  <li className="noselect">{value}</li>
);
```

Check both the _reproduced problem_ and its _solution_  by opening the sandbox in **Firefox**  :-
https://codesandbox.io/s/G6jPqD9oy

The source of solution is from [Overflowstack](https://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting-using-css)
