### ISSUE TITLE
How to sortable with the <tr> table

### ISSUE THREAD

**Issue by vxba** [clauderic/react-sortable-hoc#361]
I'm trying to sort the tr of the table, it can sorting but the SortableGhost display not correctly.

**Comment by darkrift** [comment]
I'm having the same issue, I was actually thinking of adding a css rule "body > tr { display: table }" but it doesn't seem to apply to my element.

Anyone have an idea ?

**Comment by MartinsLapsa** [comment]
Just use `helperClass` prop to add a class to dragging item to style it the same way as your table.
```
.sorting-row {
  td {
    /* necessary css rules */
  }
}
```

**Comment by christiangenco** [comment]
I had this problem specifically with [Bootstrap tables](https://getbootstrap.com/docs/3.3/css/#tables). I fixed it with a combination of @MartinsLapsa's and @darkrift's answers:

```scss
body > tr {
  display: table !important;

  td {
    padding: 8px;
    line-height: 1.428571429;
    vertical-align: top;
    border-top: 1px solid #ddd;
  }
}
```
