### ISSUE TITLE
Problem with rtl direction

### ISSUE THREAD

**Issue by smmoosavi** [clauderic/react-sortable-hoc#370]
When I use rtl direction for container sort is not working correctly

demo: https://jsfiddle.net/eckfano0/2/

```css
.item {
  cursor: move;
  padding: 8px;
  border: 1px solid red;
}

.container {
  display: flex;
  flex-direction: row;
  direction: rtl;
}
```
Is there any way to support rtl directino?
